name: allen-decoder
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - jupyter
  - jupyterlab
  - pandas
  - h5py
  - pip
  - pip:
    - allensdk
    - umap-learn       # optional: for UMAP manifold
